config/routes.rb
Rails.application.routes.draw do

  get 'topics/new'
  get 'sessions/new'
  get 'users/new'
  get 'pages/index'
  get 'pages/index'
  root 'pages#index'
  get 'pages/help'
  get "topics/index" => "topics#index"
  get "topics/:id" => "topics#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :topics
  resources :comments
  # get 'comments/new/:topic_id' => 'comments#new'

  get 'favorites/index'
  get '/favorites', to: 'favorites#index'
  post '/favorites', to: 'favorites#create'
  post "favorites/:topic_id/create" => "favorites#create"
  post "favorites/:topic_id/destroy" => "favorites#destroy"
  get "topics/:id/edit" => "topics#edit"
  post "topics/:id/update" => "topics#update"
  post "topics/:id/destroy" => "topics#destroy"

  get 'comments/index'
  get 'comments/new'

  get "users/:id/favorites" => "users#favorites"
  get "users/id" => "users#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :user_id,presence:true
  validates :topic_id,presence:true
  validates :description,presence:true

  belongs_to :user
  belongs_to :topic
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :topic


end

app/models/topic.rb
class Topic < ApplicationRecord
  has_one_attached :image
  validates :user_id, presence: true
  validates :image, presence: true
  validates :description, presence: true
  belongs_to :user
  has_many :favorite_users
  # mount_uploader :image, ImageUploader
  has_many :comments
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 15}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, format:{ with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i }
# /\A(?=\d{0,99}+[a-z])(?=[a-z]{0,99}+\d)[a-z\d]{8,100}+\z/i

  has_secure_password

  has_many :topics
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: 'topic'
  has_many :comments
  has_many :favorites_comments, through: :favorites, source: 'comment'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments_topics = current_user.comments_topics
  end

  def new
    @comment = Comment.new
    @comment.topic_id = params[:topic_id]
    if !current_user.nil?
      @login_comment_id = current_user.id
    end
    @topic = Topic.find_by(id: params[:topic_id])
    @favorites_count = Favorite.where(topic_id: params[:topic_id]).count
  end

  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      redirect_to topics_path, success: 'コメントしました'
    else
      redirect_to "/comments/new?topic_id=" + params[:comment][:topic_id], danger: "コメントに失敗しました"
    end
  end
  #   @comment = current_user.comments.new(comment_params)
  #   # Comment.new(comment_params)
  #   if @comment.save
  #    redirect_to topics_path, success: 'Comment completed'
  #   else
  #     # redirect_to topics_path, danger: 'Posting comment failed'
  #     flash.now[:danger] = 'Posting comment failed'
  #     render :new
  #   end
  # end

  private
  def comment_params
    params.require(:comment).permit(:user_id, :topic_id, :description)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_topics = current_user.favorite_topics
  end
  
  def create
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.topic_id = params[:topic_id]
    favorite.save
      redirect_to topics_path, success: 'いいねしました'
        # redirect_to topics_path, danger: 'Favorite registration failed'
  end

  def destroy
    @favorite = Favorite.find_by(
      user_id: current_user.id,
      topic_id: params[:topic_id]
    )
    @favorite.destroy
      redirect_to topics_path
      # flash.now[:danger] = 'いいねを取り消しました'
      # ("/topics/#{params[:topic_id]}")
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @topics = Topic.all.includes(:favorite_users,:comments)
  end

  def help
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to topics_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end


  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end

  private
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

private
def session_params
  params.require(:session).permit(:email, :password)
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.all.includes(:favorite_users,:comments)
  end

  def show
    @topic = Topic.find_by(id: params[:id])
    @user = @topic.user
    @favorites_count = Favorite.where(topic_id: @topic.id).count
  end

  def new
    @topic = Topic.new
    @topic = current_user.topics.build
  end

  def create
    @topic = current_user.topics.new(topic_params)
    if @topic.save
      redirect_to topics_path, success: '投稿しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end

  # def create
  #   redirect_to("/topics/index")
  # end

  def edit
    @topic = Topic.find_by(id: params[:id])

    # if @topic.checkbox == "true"
    #   @topic.checkbox = true
    # end
  end

  def update
    @topic = Topic.find_by(id: params[:id])
    @topic.update topic_params
    @topic.description = params[:topic][:description]
    # @topic.textbox = params[:topic][:textbox]
    # @topic.pulldown = params[:topic][:pulldown]
    # @topic.checkbox = params[:topic][:checkbox] ? "true" : "false"
    # @topic.radiobutton = params[:topic][:radiobutton]
    if @topic.save
      redirect_to topics_path, success: '投稿を編集しました'
    else
      flash.now[:danger] = "descriptionを入力して下さい"
      render("topics/edit")
    end
  end

  def destroy
    @topic = Topic.find_by(id: params[:id])
    @topic.destroy
    redirect_to("/topics/index")
  end

  private
  def topic_params
    params.require(:topic).permit(:image, :description, :textbox, :pulldown, :radiobutton, :checkbox)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    #binding.pry
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success:'登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end

  def favorites
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url user
    return user.profile_photo unless user.profile_photo.blank?
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg"
  end

  def logged_in?
  !current_user.nil?
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add comment</h1>

        <h2 class="topic-author">
          <%= @topic.user.name %>
        </h2>

        <% if @topic.image.attached? %>
         <%= image_tag @topic.image, class:'comment-image' %>
        <% end %>

        <div class="icons-left">
         <% if !current_user.nil? %>
           <% if Favorite.find_by(user_id:current_user.id,topic_id:@topic.id) %>
             <%= link_to("/favorites/#{@topic.id}/destroy", {method: "post"}) do %>
               <span class="fa fa-heart favorite-btn-unfavorite"></span>
             <% end %>
           <% else %>
             <%= link_to("/favorites/#{@topic.id}/create", {method: "post"}) do %>
               <span class="fa fa-heart favorite-btn"></span>
             <% end %>
           <% end %>

           <%= @favorites_count %>
        <% else %>
            <%= link_to("/", {method: "get"}) do %>
              <span class="fa fa-heart favorite-btn"></span>
            <% end %>
        <% end %>
         <%= link_to new_comment_path(topic_id: @topic.id), method: :get do %>
            <%= image_tag 'icons/comment.png', class: 'comment-icon' %>
          <% end %>
          <%= @topic.comments.count %>
        </div>

        <p class="topic-text">
          <%= @topic.description %>
        </p>
        <% if @topic.comments.count != 0 %>
           <h3 class="topic-text">コメント</h3>
         <% end %>
         <% @topic.comments.each do |comment| %>
           <p class="topic-text">
             <%= comment.description %>
           </p>
         <% end %>

         <%= form_for [@comment] do |f| %>
          <div class="form-group-comment">
          <%= f.hidden_field :topic_id, :value=> params[:topic_id] %>
          <%= f.hidden_field :user_id, :value=> @login_comment_id %>
          <% if !current_user.nil? %>
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          <% end %>
          </div>
          <% if !current_user.nil? %>
            <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @favorite_topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <% if topic.image.attached? %>
             <%= image_tag topic.image %>
           <% end %>

            <%= link_to new_comment_path(topic_id: topic.id), method: :get do %>
              <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <% end %>

            <p class="topic-text">
              <%= topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <title>Pictgram2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
      <% end %>

      <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
        <div class="container">
          <%= link_to root_path do %>
            <span><%= image_tag "icons/logo.png", class: "navbar-brand" %></span>
          <% end %>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li>
                <%= link_to user_path(current_user), method: :get do %>
                  <%= image_tag "icons/register.png" %>
                <% end %>
              </li>
              <li>
                <%= link_to topics_path do %>
                  <%= image_tag "icons/topics.png" %>
                <% end %>
              </li>
              <li>
                <%= link_to favorites_index_path do %>
                  <%= image_tag "icons/heart.png" %>
                <% end %>
              </li>
              <li>
                <%= link_to new_topic_path do %>
                  <%= image_tag "icons/camera.png" %>
                <% end %>
              </li>
              <li>
                <%= link_to logout_path, method: :delete do %>
                  <%= image_tag "icons/logout.png" %>
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to new_user_path do %>
                  <%= image_tag "icons/register.png" %>
                <% end %>
              </li>
              <li>
                <%= link_to login_path do %>
                  <%= image_tag "icons/login.png" %>
                <% end %>
              </li>
        　　<% end %>
          </ul>
        </div>
      </nav>

    <%= yield %>

    <script>
      $(function(){
        $(".alert").fadeOut(8000);
      });
    </script>
  </body>
</html>

app/views/pages/help.html.erb
<h1>ヘルプページです</h1>

app/views/pages/index.html.erb
<% if logged_in? %>
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <div class="row">
      <h1 class="text-white">Share happiness with you</h1>
      <h2 class="text-white">Pictgram is a service that you can post photos.</h2>
      <div class="col-md-offset-3 col-md-3" >
        <% unless logged_in? %>
          <%= link_to 'Sign in', new_user_path, class: 'btn btn-block btn-white' %>
        <% end %>
      </div>
      <div class="col-md-3">
        <% unless logged_in? %>
          <%= link_to 'Log in', login_path, class: 'btn btn-block btn-white' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% else %>
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <div class="row">
      <h1 class="text-white">Share happiness with you</h1>
      <h2 class="text-white">Pictgram is a service that you can post photos.</h2>
      <div class="col-md-offset-3 col-md-3" >
        <% unless logged_in? %>
          <%= link_to 'Sign in', new_user_path, class: 'btn btn-block btn-white' %>
        <% end %>
      </div>
      <div class="col-md-3">
        <% unless logged_in? %>
          <%= link_to 'Log in', login_path, class: 'btn btn-block btn-white' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>

            <%= link_to login_path(id: topic.id), method: :get do %>
              <% if topic.image.attached? %>
                <%= image_tag topic.image %>
              <% end %>
            <% end %>

            <% if !current_user.nil? %>
              <% if Favorite.find_by(user_id:current_user.id,topic_id:topic.id) %>
                <%= link_to("/favorites/#{topic.id}/destroy", {method: "post"}) do %>
                  <span class="fa fa-heart favorite-btn-unfavorite"></span>
                <% end %>
              <% else %>
                <%= link_to("/favorites/#{topic.id}/create", {method: "post"}) do %>
                  <span class="fa fa-heart favorite-btn"></span>
                <% end %>
              <% end %>
              <%= topic.favorites.count %>
            <% end %>

            <%= link_to login_path(topic_id: topic.id), method: :get do %>
              <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <% end %>
            <%= topic.comments.count %>

            <p class="topic-text">
              <%= topic.description %>
            </p>

            <% if topic.comments.count != 0 %>
               <h3 class="topic-text">コメント</h3>
             <% end %>
            <% topic.comments.each do |comment| %>
               <p class="topic-text">
                 <%= comment.description %>
               </p>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<% end %>

app/views/topics/edit.html.erb
<div class="topics-edit">
  <div class="container">
    <h1 class="form-heading">編集する</h1>
    <%= form_for @topic do |f| %>

    <div class="form">
      <div class="form-body">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control description-text' %>
        <%= f.submit '保存', class: 'btn btn-black btn-lg' %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>

            <%= link_to topic_path(id: topic.id), method: :get do %>
              <% if topic.image.attached? %>
                <%= image_tag topic.image %>
              <% end %>
            <% end %>

            <% if !current_user.nil? %>
              <% if Favorite.find_by(user_id:current_user.id,topic_id:topic.id) %>
                <%= link_to("/favorites/#{topic.id}/destroy", {method: "post"}) do %>
                  <span class="fa fa-heart favorite-btn-unfavorite"></span>
                <% end %>
              <% else %>
                <%= link_to("/favorites/#{topic.id}/create", {method: "post"}) do %>
                  <span class="fa fa-heart favorite-btn"></span>
                <% end %>
              <% end %>
              <%= topic.favorites.count %>
            <% end %>

            <%= link_to new_comment_path(topic_id: topic.id), method: :get do %>
              <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <% end %>
            <%= topic.comments.count %>

            <p class="topic-text">
              <%= topic.description %>
            </p>

            <% if topic.comments.count != 0 %>
               <h3 class="topic-text">コメント</h3>
             <% end %>
            <% topic.comments.each do |comment| %>
               <p class="topic-text">
                 <%= comment.description %>
               </p>
            <% end %>
           </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="topic-text-center">Add Picture</h1>
          <%= form_for @topic do |f| %>
          <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :image %>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>


            <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
          <% end %>

      </div>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<div class="main topics-show topic-index-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-md-offset-3"></div>
      <div class="col-md-6 col-md-offset-3">
        <div class="topic-index-single">
          <h2 class="topic-author">
            <%= @topic.user.name %>
          </h2>

          <% if @topic.image.attached? %>
           <%= image_tag @topic.image %>
          <% end %>

          <% if Favorite.find_by(user_id:current_user.id,topic_id:@topic.id) %>
           <%= link_to("/favorites/#{@topic.id}/destroy", {method: "post"}) do %>
             <span class="fa fa-heart favorite-btn-unfavorite"></span>
           <% end %>
          <% else %>
           <%= link_to("/favorites/#{@topic.id}/create", {method: "post"}) do %>
             <span class="fa fa-heart favorite-btn"></span>
           <% end %>
          <% end %>

          <%= @favorites_count %>
          <%= link_to new_comment_path(topic_id: @topic.id), method: :get do %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
          <% end %>
          <%= @topic.comments.count %>

          <p class="topic-text">
            <%= @topic.description %>
          </p>
          <% if @topic.comments.count != 0 %>
             <h3 class="topic-text">Comments</h3>
          <% end %>
          <% @topic.comments.each do |comment| %>
            <p class="topic-text">
            <%= comment.description %>
            </p>
          <% end %>

          <div class="topic-menus">
            <% if logged_in? && @topic.user_id == current_user.id %>
              <%= link_to '編集', edit_topic_path%>
              <%= link_to '削除', topic_path(@topic), method: :delete,
              data: {confirm: "本当にいいですか"} %>
                <%# <%= link_to("編集", "/topics/#{@topic.id}/edit") %>
                <%# <%= link_to("削除", "/topics/#{@topic.id}/destroy",{method:"post"}) %>
            <% end %>
          </div>
         </div>
        <div class="col-md-3 col-md-offset-3"></div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign in</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%# <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control',placeholder: "ユーザー名(半角英数字15文字以内)" %>
          </div>
          <div class="form-group">
            <%# <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control',placeholder: "メールアドレス" %>
          </div>
          <div class="form-group">
            <%# <%= f.label :password, class: 'text-white'  %>
            <%= f. password_field :password, class: 'form-control',placeholder: "パスワード(半角英数字混合8〜32文字)" %>
          </div>
          <div class="form-group">
            <%# <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control',placeholder: "パスワード(確認用再入力)" %>
          </div>

          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
          <%= link_to 'アカウントをお持ちの方はこちら', login_path, class: 'sign-in-navigation' %>
        </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile-wrap">
  <div class="row">
    <div class="col-md-5 text-center">
      <%= image_tag avatar_url(@user), class: "round-img" %>
    </div>
    <div class="col-md-5">
      <div class="user-row">
        <h1 class="user-name"><%= @user.name %></h1>
        <p class="user-mail"><%= @user.email %></p>
        <%= link_to "プロフィールを編集", topic_path, class: "btn btn-outline-dark common-btn edit-profile-btn" %>
      </div>
    </div>
  </div>
</div>